% -------------------------------------------------------------------
%  Generated by MATLAB on 19-Dec-2024 15:44:07
%  MATLAB version: 24.2.0.2740171 (R2024b) Update 1
% -------------------------------------------------------------------
saveVarsMat = load('sad_plot_code_only_19_dec.mat');

A0 = ...
  [1 0 0;
   0 1 0;
   0 0 1];

A1 = 0.02;

A2 = 0.02;

A3 = 0.02;

C_d = 2.1;

DCM_data = saveVarsMat.DCM_data; % <3x3x100001 double> too many elements

DCM_struct = saveVarsMat.DCM_struct; % <1x1 struct> too many elements at DCM_struct.time

F_e = 1358;

G = 6.6743E-11;

Gyroscope = struct;
Gyroscope.A_epsilon = ...
  [1 0 0;
   0 1 0;
   0 0 1];
Gyroscope.Gain = 1;
Gyroscope.sample_time = 0.1;
Gyroscope.ARW_standard_deviation = 0.001;
Gyroscope.ARW_variance = 1E-6;
Gyroscope.ARW_mean_value = 0;
Gyroscope.bias_gyro = 0;

HS = struct;
HS.Misalignment_matrix = ...
  [1 0 0;
   0 1 0;
   0 0 1];
HS.FOV = 6.2831853071795862;

I = ...
  [1.0090000000000001 0 0;
   0 0.251 0;
   0 0 0.91599999999999993];

M_Earth = 5.972E+24;

P = 4.5266666666666668E-6;

R_Earth = 6.378E+6;

R_sun = 1.4959787E+11;

S_N = saveVarsMat.S_N; % <100001x3 double> too many elements

Surfaces_Matrix = [0.06; 0.06; 0.06; 0.06; 0.04; 0.04; 0.12; 0.12; 0.12; ...
                   0.12];

T_sun = 3.1536E+7;

Theta_m = 0.2007128639793479;

Versor_Surfaces_Matrix = ...
  [1 0 -1 0 0 0 1 -1 1 -1;
   0 1 0 -1 0 0 0 0 0 0;
   0 0 0 0 1 -1 0 0 0 0];

a = 6.943E+6;

alpha_1 = 0.5;

alpha_2 = 0.5;

ans = 10;

areas = [0.02263 0.07705515 0.034050000000000004 0.02263 0.07705515 0.034050000000000004 ...
         0.10539749999999999 0.10539749999999999];

c = 0.008187;

directions = ...
  [1 0 0;
   0 1 0;
   0 0 1;
   -1 0 0;
   0 -1 0;
   0 0 -1;
   0 0 1;
   0 0 1];

e = 0;

epsilon = 0.4093;

g_01 = -29404.8;

g_11 = -1450.9;

h_11 = 4652.5;

heights = [0.2263 0.2263 0 0.2263 0.2263 0 0 0];

i = 0.8;

j_B = [0.01; 0.05; 0.01];

length_width_ratios = [2.263 0.66461086637298084 3.4050000000000002 2.263 ...
                       0.66461086637298084 3.4050000000000002 0.88550724637681166 ...
                       0.88550724637681166];

lens = [0 0.1 0.1 0 0.1 0.1 0.3055 0.3055];

n = 0.0010912946182439079;

n_sun = 1.9923849908611068E-7;

out = saveVarsMat.out; % <1x1 Simulink.SimulationOutput> unsupported class

position = ...
  [0.1 0 0;
   0 0.1 0;
   -0.1 0 0;
   0 -0.1 0;
   0 0 0.15;
   0 0 -0.15;
   0 0.45 0;
   0 0.45 0;
   0 -0.45 0;
   0 -0.45 0];

positions = ...
  [0.17025 0 -0.008187;
   0 0.05 -0.008187;
   0 0 0.104963;
   -0.17025 0 -0.008187;
   0 -0.05 -0.008187;
   0 0 -0.121337;
   0 0.22249999999999998 0.104963;
   0 -0.22249999999999998 0.104963];

r_N = saveVarsMat.r_N; % <100001x3 double> too many elements

rhoD_vector = [0.1; 0.1; 0.1; 0.1; 0.1; 0.1; 0.1; 0.1; 0.1; 0.1];

rhoS_vector = [0.5; 0.5; 0.5; 0.5; 0.5; 0.5; 0.5; 0.5; 0.5; 0.5];

scaleFactor = 2.0E+6;

theta0 = 0;

time = saveVarsMat.time; % <100001x1 double> too many elements

timestep = 0.1;

w0 = [0.001; 0.001; 0.02];

w_Earth = 7.29E-5;

widths = [0.1 0.3405 0.3405 0.1 0.3405 0.3405 0.345 0.345];

clear saveVarsMat;
